import React from 'react';
import GhostLogo from './assets/ghost-navbar-logo.svg';
import ExoNav from './ExoNav';
import { ArrowLeft, Edit3, Plus, Search, Trash2, UserRound, Building2, Phone, MapPin } from 'lucide-react';
import './exo-clientes.css';

const KEY='exo_customers_v1';
const TYPES=['Persona','Empresa'];
const STATUSES=['Activo','Inactivo'];
const seed=[
{id:'EXO-CLI-0001',type:'Empresa',name:'Distribuidora Norte',nit:'10293847',phone:'70000001',email:'ventas@distribuidoranorte.bo',address:'Cochabamba',status:'Activo'},
{id:'EXO-CLI-0002',type:'Empresa',name:'Limpieza Hogar',nit:'20394857',phone:'70000002',email:'contacto@limpiezahogar.bo',address:'Quillacollo',status:'Activo'},
{id:'EXO-CLI-0003',type:'Empresa',name:'Comercial Andina',nit:'30495867',phone:'70000003',email:'compras@comercialandina.bo',address:'Sacaba',status:'Activo'}
];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(Array.isArray(x)&&x.length)return x}catch{}return seed}
export default function ExoClientes(){
 const [items,setItems]=React.useState(load),[selectedId,setSelectedId]=React.useState(load()[0]?.id),[q,setQ]=React.useState(''),[filter,setFilter]=React.useState('Todos'),[modal,setModal]=React.useState(false),[editing,setEditing]=React.useState(null);
 React.useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(items));document.title='EXO · Clientes | Ghost W&SD'},[items]);
 const filtered=items.filter(c=>(filter==='Todos'||c.status===filter)&&(!q.trim()||[c.id,c.name,c.nit,c.phone,c.email,c.address].join(' ').toLowerCase().includes(q.toLowerCase())));
 const selected=items.find(x=>x.id===selectedId)||filtered[0];
 const save=c=>{setItems(a=>a.some(x=>x.id===c.id)?a.map(x=>x.id===c.id?c:x):[c,...a]);setSelectedId(c.id);setModal(false);setEditing(null)};
 const del=id=>{if(confirm('¿Eliminar este cliente?')){setItems(a=>a.filter(x=>x.id!==id));setSelectedId('')}};
 return <div className="exo-customers">
 <header className="exo-customers-header"><a href="https://ghost.medunzcorp.com"><img src={GhostLogo} alt="Ghost Web & Software Designer"/></a><div><span>GHOST W&amp;SD</span><strong>EXO / CLIENTES</strong></div><a className="exo-customers-back" href="https://ghost.medunzcorp.com/exo/pedidos"><ArrowLeft size={15}/> Pedidos</a></header>
  <ExoNav active="clientes" />
 <main className="exo-customers-main">
 <section className="exo-customers-hero"><div><span className="exo-kicker">EXO · CARTERA COMERCIAL</span><h1>Clientes.<br/><em>Relaciones que permanecen.</em></h1><p>Centraliza la información comercial de personas y empresas para reutilizarla en pedidos, ventas, entregas y futuras comunicaciones.</p></div><div className="exo-customers-mark"><UserRound size={38}/><span>{items.length}<br/>CLIENTES</span></div></section>
 <section className="exo-customers-toolbar"><div className="exo-customers-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, NIT, teléfono o correo..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><button className="exo-customers-button primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus size={16}/> Nuevo cliente</button></section>
 <section className="exo-customers-layout"><div className="exo-customers-list"><div className="exo-list-head"><div><span>CLIENTES REGISTRADOS</span><h2>{filtered.length} registros</h2></div><UserRound size={20}/></div>{filtered.map(c=><button key={c.id} className={selected?.id===c.id?'exo-customer-row active':'exo-customer-row'} onClick={()=>setSelectedId(c.id)}><span className="exo-avatar">{c.type==='Empresa'?<Building2 size={17}/>:<UserRound size={17}/>}</span><span className="exo-customer-name"><b>{c.name}</b><small>{c.id} · {c.nit||'Sin NIT'}</small></span><span className="exo-customer-status">{c.status}</span></button>)}</div>
 <aside className="exo-customer-detail">{selected?<><div className="exo-detail-top"><span>FICHA DE CLIENTE</span><span className="exo-customer-status large">{selected.status}</span></div><div className="exo-customer-id">{selected.id}</div><h2>{selected.name}</h2><span className="exo-type">{selected.type}</span><div className="exo-contact-grid"><div><Phone size={17}/><span>Teléfono<strong>{selected.phone||'No registrado'}</strong></span></div><div><Building2 size={17}/><span>NIT<strong>{selected.nit||'No registrado'}</strong></span></div><div><MapPin size={17}/><span>Dirección<strong>{selected.address||'No registrada'}</strong></span></div><div><span className="exo-email-symbol">@</span><span>Correo<strong>{selected.email||'No registrado'}</strong></span></div></div><div className="exo-detail-actions"><button className="exo-customers-button primary" onClick={()=>{setEditing(selected);setModal(true)}}><Edit3 size={15}/> Editar</button><button className="exo-danger" onClick={()=>del(selected.id)}><Trash2 size={15}/> Eliminar</button></div></>:<div>Selecciona un cliente.</div>}</aside></section>
 </main>{modal&&<CustomerModal initial={editing} items={items} onClose={()=>setModal(false)} onSave={save}/>}<footer className="exo-customers-footer"><span>EXO · Clientes</span><span>Ghost Web &amp; Software Designer · Medunz Corp.</span></footer>
 </div>
}
function CustomerModal({initial,items,onClose,onSave}){
 const [type,setType]=React.useState(initial?.type||'Empresa'),[name,setName]=React.useState(initial?.name||''),[nit,setNit]=React.useState(initial?.nit||''),[phone,setPhone]=React.useState(initial?.phone||''),[email,setEmail]=React.useState(initial?.email||''),[address,setAddress]=React.useState(initial?.address||''),[status,setStatus]=React.useState(initial?.status||'Activo');
 const save=e=>{e.preventDefault();if(!name.trim())return;const id=initial?.id||'EXO-CLI-'+String(Date.now()).slice(-6);if(items.some(x=>x.name.toLowerCase()===name.trim().toLowerCase()&&x.id!==initial?.id)){alert('Ya existe un cliente con ese nombre.');return}onSave({id,type,name:name.trim(),nit:nit.trim(),phone:phone.trim(),email:email.trim(),address:address.trim(),status})};
 return <div className="exo-modal-backdrop"><form className="exo-customer-modal" onSubmit={save}><div className="exo-modal-head"><div><span>CARTERA COMERCIAL</span><h2>{initial?'Editar cliente':'Nuevo cliente'}</h2></div><button type="button" onClick={onClose}>×</button></div><div className="exo-form-grid"><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></label><label className="full">Nombre / razón social<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre del cliente o empresa" required/></label><label>NIT / CI<input value={nit} onChange={e=>setNit(e.target.value)}/></label><label>Teléfono<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Correo electrónico<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Dirección<input value={address} onChange={e=>setAddress(e.target.value)}/></label></div><div className="exo-modal-foot"><button type="button" className="exo-customers-button light" onClick={onClose}>Cancelar</button><button className="exo-customers-button primary">Guardar cliente</button></div></form></div>
}