import React from 'react';
import GhostLogo from './assets/ghost-navbar-logo.svg';
import { Activity, AlertTriangle, ArrowUpRight, Boxes, CheckCircle2, ChevronRight, ClipboardList, Clock3, Package, ShoppingCart, TrendingUp, Users, Warehouse, XCircle } from 'lucide-react';
import './exo-dashboard.css';

const KEYS={products:'exo_products_v1',presentations:'exo_presentations_v1',sku:'exo_sku_catalog_v1',customers:'exo_customers_v1',orders:'exo_orders_v1',inventory:'exo_inventory_v1',lots:'exo_lots_v1',movements:'exo_movements_v1',lotInventory:'exo_lot_inventory_v1'};
const PRODUCT_SEED=[['VAJ','Vajillero'],['LPI','Limpia Piso'],['SHA','Shampoo'],['SGR','Saca Grasa'],['LVR','Lava Ropa'],['JLI','Jabón Líquido'],['CWS','Car Wash']].map(([id,name])=>({id,name,status:'Activo'}));
const PRESENTATION_SEED=[['VAJ','Vajillero',['1 L','3 L','10 L']],['LPI','Limpia Piso',['1 L','3 L','10 L']],['SHA','Shampoo',['500 ml','1 L','3 L','10 L']],['SGR','Saca Grasa',['1 L','3 L','10 L']],['LVR','Lava Ropa',['3 L','5 L','10 L']],['JLI','Jabón Líquido',['1 L','3 L','10 L']],['CWS','Car Wash',['500 ml','1 L','3 L','10 L']]].flatMap(([code,product,sizes])=>sizes.map(size=>({id:code+'-'+size.replace(/\s/g,''),productCode:code,product,size,status:'Activo'})));
const SKU_SEED=PRESENTATION_SEED.map(x=>({sku:'EXO-'+x.productCode+'-'+(x.size==='500 ml'?'500':x.size.replace(' L','').padStart(3,'0')),product:x.product,presentation:x.size,status:'Activo'}));
const INVENTORY_SEED=SKU_SEED.map((x,i)=>({...x,stock:i===3?500:[18,65,120,42,80,35,12,55,90,25,40,15,70,32,110,28,45,18,60,24,75,16,50][i],reserved:i===3?24:([2,5,8].includes(i)?8:0)}));
const LOT_SEED=[{id:'EXO-2026-001',lot:'EXO-2026-001',product:'Shampoo',size:'1 L',sku:'EXO-SHA-001',expires:'2028-10-01',quantity:500,status:'Liberado'},{id:'EXO-2026-002',lot:'EXO-2026-002',product:'Vajillero',size:'1 L',sku:'EXO-VAJ-001',expires:'2028-10-03',quantity:350,status:'En producción'},{id:'EXO-2026-003',lot:'EXO-2026-003',product:'Lava Ropa',size:'3 L',sku:'EXO-LVR-003',expires:'2028-10-05',quantity:250,status:'En cuarentena'},{id:'EXO-2026-004',lot:'EXO-2026-004',product:'Car Wash',size:'500 ml',sku:'EXO-CWS-500',expires:'2028-10-06',quantity:420,status:'Planificado'}];
const CUSTOMER_SEED=[{id:'EXO-CLI-0001',name:'Distribuidora Norte',status:'Activo'},{id:'EXO-CLI-0002',name:'Limpieza Hogar',status:'Activo'},{id:'EXO-CLI-0003',name:'Comercial Andina',status:'Activo'}];
const ORDER_SEED=[{id:'EXO-PED-0001',date:'2026-10-05',customer:'Distribuidora Norte',status:'Confirmado',discount:0,lines:[{sku:'EXO-SHA-001',product:'Shampoo',presentation:'1 L',qty:12,price:20.5}]},{id:'EXO-PED-0002',date:'2026-10-06',customer:'Limpieza Hogar',status:'En entrega',discount:10,lines:[{sku:'EXO-VAJ-003',product:'Vajillero',presentation:'3 L',qty:8,price:30.5}]},{id:'EXO-PED-0003',date:'2026-10-07',customer:'Comercial Andina',status:'Borrador',discount:0,lines:[{sku:'EXO-CWS-010',product:'Car Wash',presentation:'10 L',qty:4,price:176}]}];
function read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)&&v.length?v:fallback}catch{return fallback}}
const money=n=>'Bs '+Number(n||0).toLocaleString('es-BO',{minimumFractionDigits:2,maximumFractionDigits:2});
const qty=n=>Number(n||0).toLocaleString('es-BO');
const orderTotal=o=>Math.max(0,(o.lines||[]).reduce((s,l)=>s+(Number(l.qty)||0)*(Number(l.price)||0),0)-(Number(o.discount)||0));
const scoreColor=s=>s>=85?'good':s>=65?'watch':'risk';

export default function ExoDashboard(){
 const [tick,setTick]=React.useState(0);
 React.useEffect(()=>{document.title='EXO · Dashboard operativo';const id=setInterval(()=>setTick(x=>x+1),30000);return()=>clearInterval(id)},[]);
 const products=read(KEYS.products,PRODUCT_SEED),presentations=read(KEYS.presentations,PRESENTATION_SEED),sku=read(KEYS.sku,SKU_SEED),customers=read(KEYS.customers,CUSTOMER_SEED),orders=read(KEYS.orders,ORDER_SEED),inventory=read(KEYS.inventory,INVENTORY_SEED),lots=read(KEYS.lots,LOT_SEED),movements=read(KEYS.movements,[]),lotInventory=read(KEYS.lotInventory,[]);
 const activeProducts=products.filter(x=>x.status!=='Inactivo').length,activeCustomers=customers.filter(x=>x.status!=='Inactivo').length;
 const availableInventory=inventory.reduce((s,x)=>s+Math.max(0,Number(x.stock||0)-Number(x.reserved||0)),0),physicalInventory=inventory.reduce((s,x)=>s+Number(x.stock||0),0),reservedInventory=inventory.reduce((s,x)=>s+Number(x.reserved||0),0);
 const lowStock=inventory.filter(x=>{const a=Math.max(0,Number(x.stock||0)-Number(x.reserved||0));return a>0&&a<=20}),outOfStock=inventory.filter(x=>Math.max(0,Number(x.stock||0)-Number(x.reserved||0))===0);
 const releasedLots=lots.filter(x=>x.status==='Liberado'),quarantineLots=lots.filter(x=>x.status==='En cuarentena'),productionLots=lots.filter(x=>x.status==='En producción'),plannedLots=lots.filter(x=>x.status==='Planificado');
 const openOrders=orders.filter(x=>!['Entregado','Cancelado','Rechazado'].includes(x.status)),confirmedOrders=orders.filter(x=>x.status==='Confirmado'),preparationOrders=orders.filter(x=>['Preparando','Listo para entrega'].includes(x.status)),deliveryOrders=orders.filter(x=>x.status==='En entrega'),deliveredOrders=orders.filter(x=>x.status==='Entregado'),rejectedOrders=orders.filter(x=>['Cancelado','Rechazado'].includes(x.status)),draftOrders=orders.filter(x=>x.status==='Borrador');
 const salesPipeline=openOrders.reduce((s,o)=>s+orderTotal(o),0),confirmedValue=confirmedOrders.reduce((s,o)=>s+orderTotal(o),0),deliveredValue=deliveredOrders.reduce((s,o)=>s+orderTotal(o),0),avgTicket=orders.length?orders.reduce((s,o)=>s+orderTotal(o),0)/orders.length:0,unitsOrdered=openOrders.reduce((s,o)=>s+(o.lines||[]).reduce((a,l)=>a+(Number(l.qty)||0),0),0);
 const entries=movements.filter(x=>x.type==='Entrada').reduce((s,x)=>s+Number(x.quantity||0),0),exits=movements.filter(x=>x.type==='Salida').reduce((s,x)=>s+Number(x.quantity||0),0),reservations=movements.filter(x=>x.type==='Reserva').reduce((s,x)=>s+Number(x.quantity||0),0);
 const operationalScore=Math.max(0,Math.min(100,100-outOfStock.length*5-lowStock.length*2-quarantineLots.length*5+ (releasedLots.length?2:0)));
 const salesScore=Math.max(0,Math.min(100,orders.length?Math.min(100,55+confirmedOrders.length*8+deliveryOrders.length*5+deliveredOrders.length*10-rejectedOrders.length*7):0));
 const serviceScore=Math.max(0,Math.min(100,orders.length?Math.min(100,82+deliveredOrders.length*4-rejectedOrders.length*8-draftOrders.length*2):70));
 const traceabilityScore=Math.max(0,Math.min(100,sku.length===23?Math.min(100,75+(releasedLots.length?10:0)+(lotInventory.length?10:0)+(movements.length?5:0)):Math.round((sku.length/23)*75)));
 const overall=Math.round(operationalScore*.35+salesScore*.30+serviceScore*.20+traceabilityScore*.15);
 const scoreItems=[['Operación',operationalScore,'Stock, lotes y disponibilidad'],['Ventas',salesScore,'Pedidos y pipeline comercial'],['Servicio',serviceScore,'Cumplimiento del pedido'],['Trazabilidad',traceabilityScore,'SKU, lotes y movimientos']];
 const alerts=[];
 lowStock.slice(0,4).forEach(x=>alerts.push({type:'warning',title:'Stock bajo',text:x.sku+' · '+x.product+' '+x.presentation+': '+qty(Math.max(0,x.stock-x.reserved))+' disponibles',href:'/exo/inventario'}));
 outOfStock.slice(0,3).forEach(x=>alerts.push({type:'danger',title:'Agotado',text:x.sku+' · '+x.product+' '+x.presentation,href:'/exo/inventario'}));
 quarantineLots.slice(0,3).forEach(x=>alerts.push({type:'danger',title:'Lote en cuarentena',text:x.lot+' · '+x.product+' '+x.size,href:'/exo/lotes'}));
 draftOrders.slice(0,2).forEach(x=>alerts.push({type:'info',title:'Pedido pendiente',text:x.id+' · '+x.customer+' · '+money(orderTotal(x)),href:'/exo/pedidos'}));
 if(!alerts.length)alerts.push({type:'success',title:'Operación estable',text:'No se detectaron alertas críticas con los datos actuales.',href:'#'});
 const flow=[['Borrador',draftOrders.length,'neutral'],['Confirmado',confirmedOrders.length,'blue'],['Preparación',preparationOrders.length,'orange'],['En entrega',deliveryOrders.length,'orange'],['Entregado',deliveredOrders.length,'green']];
 const topInventory=[...inventory].sort((a,b)=>(b.stock-b.reserved)-(a.stock-a.reserved)).slice(0,6);

 return <div className="exo-dashboard">
  <header className="exo-dashboard-header"><a href="https://ghost.medunzcorp.com"><img src={GhostLogo} alt="Ghost Web & Software Designer"/></a><div><span>EXO CLEAN</span><strong>TORRE DE CONTROL</strong></div><nav><a href="https://ghost.medunzcorp.com/exo/productos">Productos</a><a href="https://ghost.medunzcorp.com/exo/pedidos">Pedidos</a><a href="https://ghost.medunzcorp.com/exo/inventario">Inventario</a><a href="https://ghost.medunzcorp.com/exo/lotes">Lotes</a><a href="https://ghost.medunzcorp.com/exo/movimientos">Kardex</a></nav></header>
  <main className="exo-dashboard-main">
   <section className="exo-dashboard-hero"><div><span className="exo-kicker">EXO CLEAN · CONTROL GERENCIAL</span><h1>Dashboard.<br/><em>Una mirada sobre toda la operación.</em></h1><p>Ventas, pedidos, inventario, lotes y trazabilidad reunidos en una sola vista para detectar desviaciones y actuar a tiempo.</p></div><div className="exo-score-card"><div className="score-ring" style={{'--score':(overall*3.6)+'deg'}}><strong>{overall}</strong><span>/ 100</span></div><div><span>SCORE EXO</span><b className={scoreColor(overall)}>{overall>=85?'SALUDABLE':overall>=65?'ATENCIÓN':'RIESGO'}</b></div></div></section>
   <section className="exo-dashboard-kpis"><article className="kpi sales"><div><span>PIPELINE DE VENTAS</span><strong>{money(salesPipeline)}</strong><small>{openOrders.length} pedidos abiertos · {qty(unitsOrdered)} unidades</small></div><TrendingUp/></article><article className="kpi inventory"><div><span>DISPONIBLE</span><strong>{qty(availableInventory)} <small>u.</small></strong><small>{qty(physicalInventory)} físicas · {qty(reservedInventory)} reservadas</small></div><Warehouse/></article><article className="kpi orders"><div><span>PEDIDOS ACTIVOS</span><strong>{openOrders.length}</strong><small>{confirmedOrders.length} confirmados · {deliveryOrders.length} en entrega</small></div><ShoppingCart/></article><article className="kpi clients"><div><span>CLIENTES ACTIVOS</span><strong>{activeCustomers}</strong><small>de {customers.length} registrados</small></div><Users/></article></section>
   <section className="exo-score-section"><div className="section-title"><div><span>01 · SCORE CARD</span><h2>¿Cómo está funcionando EXO?</h2></div><span className="live"><Activity size={14}/> ACTUALIZACIÓN AUTOMÁTICA</span></div><div className="score-grid">{scoreItems.map(([label,value,desc])=><article className="score-item" key={label}><div className="score-item-head"><span>{label}</span><strong className={scoreColor(value)}>{value}</strong></div><div className="score-bar"><i style={{width:value+'%'}}/></div><small>{desc}</small></article>)}</div></section>
   <section className="exo-dashboard-grid"><article className="panel flow-panel"><div className="panel-head"><div><span>02 · FLUJO COMERCIAL</span><h2>Pedidos por etapa</h2></div><a href="https://ghost.medunzcorp.com/exo/pedidos">Ver pedidos <ArrowUpRight size={15}/></a></div><div className="flow">{flow.map(([label,value,tone],i)=><React.Fragment key={label}><div className={'flow-step '+tone}><strong>{value}</strong><span>{label}</span></div>{i<flow.length-1&&<ChevronRight className="flow-arrow" size={18}/>}</React.Fragment>)}</div><div className="flow-summary"><span>Valor confirmado <strong>{money(confirmedValue)}</strong></span><span>Valor entregado <strong>{money(deliveredValue)}</strong></span><span>Ticket promedio <strong>{money(avgTicket)}</strong></span></div></article>
   <article className="panel alerts-panel"><div className="panel-head"><div><span>03 · ALERTAS</span><h2>Lo que requiere atención</h2></div><span className="alert-count">{alerts.filter(x=>x.type!=='success').length}</span></div><div className="alerts-list">{alerts.slice(0,6).map((a,i)=><a className={'alert-row '+a.type} href={'https://ghost.medunzcorp.com'+a.href} key={i}><span className="alert-icon">{a.type==='danger'?<XCircle size={17}/>:a.type==='warning'?<AlertTriangle size={17}/>:a.type==='success'?<CheckCircle2 size={17}/>:<Clock3 size={17}/>}</span><span><b>{a.title}</b><small>{a.text}</small></span><ChevronRight size={15}/></a>)}</div></article></section>
   <section className="exo-dashboard-grid lower"><article className="panel inventory-panel"><div className="panel-head"><div><span>04 · INVENTARIO</span><h2>Disponibilidad por SKU</h2></div><a href="https://ghost.medunzcorp.com/exo/inventario">Gestionar <ArrowUpRight size={15}/></a></div><div className="inventory-list">{topInventory.map(x=>{const av=Math.max(0,x.stock-x.reserved);const pct=Math.min(100,(av/120)*100);return <div className="inventory-row" key={x.sku}><div><b>{x.sku}</b><small>{x.product} · {x.presentation}</small></div><div className="inventory-meter"><i style={{width:pct+'%'}}/></div><strong>{qty(av)} <small>u.</small></strong></div>})}</div><div className="panel-foot"><span><Boxes size={15}/> {qty(availableInventory)} unidades disponibles</span><span className={lowStock.length?'warning-text':''}>{lowStock.length} SKU con stock bajo · {outOfStock.length} agotados</span></div></article>
   <article className="panel lots-panel"><div className="panel-head"><div><span>05 · LOTES</span><h2>Estado de producción</h2></div><a href="https://ghost.medunzcorp.com/exo/lotes">Ver lotes <ArrowUpRight size={15}/></a></div><div className="lot-status-grid"><div><strong>{releasedLots.length}</strong><span>Liberados</span></div><div className="warn"><strong>{productionLots.length}</strong><span>En producción</span></div><div className="danger"><strong>{quarantineLots.length}</strong><span>Cuarentena</span></div><div><strong>{plannedLots.length}</strong><span>Planificados</span></div></div><div className="lot-focus">{releasedLots.slice(0,3).map(l=><div key={l.id}><Package size={16}/><span><b>{l.lot}</b><small>{l.product} · {l.size} · {l.expires?'Vence '+l.expires:'Sin vencimiento'}</small></span></div>)}{!releasedLots.length&&<p>No hay lotes liberados actualmente.</p>}</div></article></section>
   <section className="exo-dashboard-bottom"><article className="mini-panel"><ClipboardList/><div><span>CATÁLOGO</span><strong>{activeProducts} productos · {presentations.length} presentaciones</strong><small>{sku.length} SKU codificados</small></div><a href="https://ghost.medunzcorp.com/exo/codificacionsku">Abrir <ChevronRight size={15}/></a></article><article className="mini-panel"><Activity/><div><span>KARDEX</span><strong>{movements.length} movimientos</strong><small>{qty(entries)} entradas · {qty(exits)} salidas · {qty(reservations)} reservas</small></div><a href="https://ghost.medunzcorp.com/exo/movimientos">Abrir <ChevronRight size={15}/></a></article><article className="mini-panel"><Users/><div><span>CLIENTES</span><strong>{activeCustomers} activos</strong><small>Base comercial conectada a pedidos</small></div><a href="https://ghost.medunzcorp.com/exo/clientes">Abrir <ChevronRight size={15}/></a></article></section>
  </main><footer className="exo-dashboard-footer"><span>EXO CLEAN · Torre de control</span><span>Ghost Web &amp; Software Designer · Medunz Corp.</span><span>Actualizado automáticamente</span></footer>
 </div>;
}
